### ISSUE TITLE
Jumpscript not working

### ISSUE THREAD

**Issue by Zarenx** [7Cav/cScripts#1005]
We tried to do a line jump from a C-17 on the Charlie Company FTX, we were within the parameters but the script would not work.

**Comment by pool011** [comment]
Upon further investigation, the issue appears to arise from a locality issue. The only person who has the jump script initialized is the Zeus who placed the object down.

**Comment by AndreasBrostrom** [comment]
Was the C-17 placed by a zeus?
And was it placed by a created or predefined zeus?

**Comment by Zarenx** [comment]
jump script worked only for the Zeus that put down the aircraft and did not work at all with eden-placed vehicles. i tested all the C-130, C-130j and on the training server, i also tested the C-17 without any luck. i was well within the parameters and i had a couple of guys with the during the testing period. is this something we can look into, we can't do any airborne operations :/
