### ISSUE TITLE
Remove RHS MAAWS and RHS MAAWS Ammo from all loadouts, staging zone, crates

### ISSUE THREAD

**Issue by AndreasBrostrom** [7Cav/cScripts#1029]
Remove RHS MAAWS and RHS MAAWS Ammo from all loadouts, staging zone, crates

**Comment by pool011** [comment]
Waiting for Cav Aux update to add crew-served maaws. On backlog until then

**Comment by pool011** [comment]
@Robot-Panda15 it is time. Rally the banners. Crew-Served MAAWS has arrived to cav aux 2. Changing milestone to next version

**Comment by pool011** [comment]
#1095
