### ISSUE TITLE
Staging Zone Map Circles

### ISSUE THREAD

**Issue by Zarenx** [7Cav/cScripts#1043]
Morning, could we keep the purple staging zone map markings that we have in the debug cScripts?
It would help the players find the arsenal features, especially vehicle crews, to see where they can rekit / Customize their vehicles.

**Comment by Zarenx** [comment]
![Uploading image.png…]()

**Comment by Zarenx** [comment]
![image](https://github.com/7Cav/cScripts/assets/111392464/4254b65b-8fe5-4973-943b-19b6f05bfc92)

**Comment by AndreasBrostrom** [comment]
It is definitely possible can make them transparent with a black outline circle instead. 

How it works atm I only paint them on init. 
So ther are no markers are added after the fact only if you back out slot selection and log back in the new zones will be visible. The zones don't follow objects either so they will never disappear.

So if we want them vissable always it needs to be changed a little.

**Comment by AndreasBrostrom** [comment]
I lied it was not on init it was on zone creation.
But the markers don't gets removed if the zone or is removed and will not move.

**Comment by AndreasBrostrom** [comment]
Zona data today is:
Zone center is a object empty texture for a marker and the size.

Changing the zone object to a net I'd would make it possible to remove the zones mid mission. Using the same method as the removal of vehicle labels.
