### ISSUE TITLE
Extend the Range of rearm and refuel lines

### ISSUE THREAD

**Issue by PolySparrow** [7Cav/cScripts#1044]
This is to make it easier to rearm and refuel from FAT COW, a CH-47, for rotary assets and make it where rotors will not collide with other choppers

`force force ace_refuel_hoseLength = 15;` to
`force force ace_refuel_hoseLength = 25;`

and 

`force force ace_rearm_distance = 20;` to 
`force force ace_rearm_distance = 25;`

**Comment by AndreasBrostrom** [comment]
sure. ☺️
