### ISSUE TITLE
Training map scripting

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#11]
- [x] Make custom hint for training maps. 
- [ ] Make custom diary records (one per course or one for all. Added under the 7cav category)

### Records
- [ ] Make links to Training documents
- [x] Add flavor text
- [x] Force some one to spell and grammar check all text.

**Comment by ColdEvul** [comment]
### Reference material
- https://community.bistudio.com/wiki/createDiaryRecord
- https://community.bistudio.com/wiki/Structured_Text#Hyperlink

**Comment by ColdEvul** [comment]
`FUNC(Doc_InfoOperation)` replaces `FUNC(Doc_Info)`
`FUNC(Doc_InfoTraining)`
`FUNC(Doc_InfoCustom)`

**Comment by ColdEvul** [comment]
Being made in #1

**Comment by RaynorD** [comment]
I can be your grammar/spell checker. Already see a couple things to adjust in the above text.

Welcome! You are currently joining an official S3 Battle Staff operation. Please follow our General Orders, Code of Conduct, and orders from your commanding personnel. But most importantly: have fun! This mission is running cScripts, our mission script framework, adapted for our missions and fully customizable.

Welcome! You are currently joining an official S3 training session. Give your instructor your complete  attention, and keep a pen and paper close at hand. But most importantly: have fun! This mission is running cScripts, our mission script framework, adapted for our missions and fully customizable.

%User text% OR Welcome to this custom mission. This mission is running cScripts, our mission script framework, adapted for our missions and fully customizable.

**Comment by ColdEvul** [comment]
You could check the diary records not related to 'nine lines' and the hints for spelling errors :)  If you find or have a additional ideas  please let me know or add them :) 

https://github.com/7Cav/cScripts/tree/master/cScripts/CavFnc/functions/init
https://github.com/7Cav/cScripts/tree/master/cScripts/CavFnc/functions/init/DiaryRecord

**Comment by ColdEvul** [comment]
Argus made some
