### ISSUE TITLE
Arsenal not initializing all the equipment on mission start.

### ISSUE THREAD

**Issue by Zarenx** [7Cav/cScripts#1136]
Have had a couple of Operations for the last 2 version of cScripts where parts of the arsenal whitelist does not load on the start causing people to miss radios, demolition and other equipment. 

When kits are re-selected in the staging zone they do however gain access to the missing equipment. Is this something we could look into?

**Comment by pool011** [comment]
Can you attach additional information to this thread? What environment does this occur in, how many people are on the server when this happens, etc.?

**Comment by Zarenx** [comment]
Here is some footage that shows the issue above: 
https://www.youtube.com/live/r83vS0eS-j8?si=77Y3WX4j6ml-ByA5&t=2279

I sadly do not have any logs or recordings of the other events that people have had this issue also.

**Comment by AndreasBrostrom** [comment]
Seams like only some items are effected

- Investigate if custom casing have effect on items existing or not `ace_bannan` > `aCE_BaNAnnA`
- Investigate if ace categorys system effect the items existence radios seams effected.
- Investigate if ace sorting category is effected by custom casing  `ace_bannan` > `aCE_BaNAnnA`
