### ISSUE TITLE
Need Support for SOAR MH-47 helis

### ISSUE THREAD

**Issue by Elemtael** [7Cav/cScripts#1188]
Not entirely sure but I believe this line of code is preventing the action from becoming visible.

The ramp source is referred to as "Ramp" in the mod's files.

Courtesy of testing and examination by Hilberg and Crapachi.

https://github.com/7Cav/cScripts/blob/3416f0aeb1747fdb9a8b9655cff53feaf9a9c367/cScripts/functions/mission/fn_addLineJump.sqf#L32

**Comment by pool011** [comment]
Leaving this open just in case
