### ISSUE TITLE
Poppy_fnc_logWarning - script error on showing message

### ISSUE THREAD

**Issue by RaynorD** [7Cav/cScripts#18]
Error is thrown anytime a message is shown by Poppy, like out of space, etc. Loading our current squad leader loadout can reproduce this.

2:17:11 Error in expression <eShowWarnings") == 1}) then {
Poppy_log pushBack ["Warning", _message];
};
};

2:17:11 Error position: <pushBack ["Warning", _message];
};
};

2:17:11 Error Type Number, expected Bool
2:17:11 File C:\Users...(mission)\cScripts\Loadouts\script\functions\main\fn_logWarning.sqf, line 7

**Comment by ColdEvul** [comment]
Known issue I've just ignored it cause new Loadouts coming :P

But I've passing this one threw to the poppy dev. 
https://github.com/BaerMitUmlaut/Poppy/issues/15

**Comment by RaynorD** [comment]
I noticed it only happens when I'm the server during singleplayer testing, so not a big deal on a dedicated server.  Worst case it just throws an error in the log.

**Comment by ColdEvul** [comment]
Yeah, I assumed so much. ^^

Den 12 feb. 2017 4:53 em skrev "Dave Raynor" <notifications@github.com>:

**Comment by BaerMitUmlaut** [comment]
You guys are still on Version 1.0.0:
https://github.com/7Cav/cScripts/blob/master/cScripts/Loadouts/script/functions/script_component.hpp#L12
This was fixed in in 1.1.0. 1.2.0 is coming out soon btw!

**Comment by ColdEvul** [comment]
That is kind of hilarious due to the fact we used pre- and postloadout.
I probably messed up the update process some how or graded the repo before everything was pushed xD

Thx for clearing that one up ^^

**Comment by ColdEvul** [comment]
Fixed by #35
