### ISSUE TITLE
Crew Chief (A/1-7) loadout not spawning

### ISSUE THREAD

**Issue by redcrayonn** [7Cav/cScripts#209]
**cScripts Version:** latest

**Description:**
- The class of the crew chief seems to have changed in cScripts compared to the 'somewhat' old S3 mission composition. B_T_Helicrew_F is what the composition uses. 

**Steps to reproduce:**
- Place down air assault composition. Log into the game as Crew Chief.

**Where did the issue occur?**
- Editor (Multiplayer)

**Comment by uaon** [comment]
4.2.13 Release changed the line on cScripts\Loadouts\CfgLoadouts_AlphaClass.hpp

> class B_Helicrew_T : CAV_Alpha_Helo_CHIEF {};
To
> class B_T_Helicrew_F : CAV_Alpha_Helo_CHIEF {};

would switching this back to B_Helicrew_T have some unforeseen consequence?

**Comment by redcrayonn** [comment]
Maybe, could you not add both, perhaps add a deprecated warning and remove in like 1-2 months? Just an idea :)

**Comment by ColdEvul** [comment]
fixed in 4.3.0
