### ISSUE TITLE
enable7cavZeusModules undefined if not running achilles

### ISSUE THREAD

**Issue by RaynorD** [7Cav/cScripts#231]
https://github.com/7Cav/cScripts/blob/0259a4c22b8a0f4f51ca9d0be1322756cee63081/cScripts/CavFnc/cScripts_preInit.sqf#L141

This check is causing an undefined variable error after I added cScripts to a mission while not having achilles loaded.

**Comment by ColdEvul** [comment]
Issue caused here:

https://github.com/7Cav/cScripts/blob/0259a4c22b8a0f4f51ca9d0be1322756cee63081/cScripts/CavFnc/cScripts_preInit.sqf#L183

Possible fix add additional check or move stuff around.
