### ISSUE TITLE
Add admin panel for zeus players to quickly do mission wide options. 

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#255]
Add a admin panel for zeus players to quickly do mission wide options.

**How and what:**
- [ ] A diary record tab only avalible for zeus players.
- [ ] Only avalible for private missions? or the warning below:
- [ ] Add a large waning `Wrongly usage of this features as for any other zeus moduels may resolt in a NCS and your zeus access being revoked`
- [ ] Heal all
- [ ] Force reload if loadouts on all units.
- [ ] Force Respawn for all units. (kill all)
- [ ] Freez all ai units
- [ ] Kill all ai units

**Comment by libertybell95** [comment]
Suggest having a "Training Time Out" feature also that makes all enemy AI friendly to players with a click of a button so Squad Leads can 'pause' a training session and correct any faults during SP.
