### ISSUE TITLE
Update in game documents

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#260]
# [Documents](https://github.com/7Cav/cScripts/tree/master/cScripts/CavFnc/functions/documents)
- [ ] [fn_Doc_Info](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_Doc_Info.sqf)
- [ ] [fn_Doc_MissionControl](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_Doc_MissionControl.sqf)
- [ ] [fn_DocChklist_CFF](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocChklist_CFF.sqf)
- [ ] [fn_DocChklist_JMTASKS](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocChklist_JMTASKS.sqf)
- [ ] [fn_DocChklist_LZEXTRACT](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocChklist_LZEXTRACT.sqf)
- [ ] [fn_DocChklist_LZINSERT](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocChklist_LZINSERT.sqf)
- [ ] [fn_DocChklist_LZSPECS](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocChklist_LZSPECS.sqf)
- [ ] [fn_DocRadio_LACEACE](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocRadio_LACEACE.sqf)
- [ ] [fn_DocRadio_MEDEVAC](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocRadio_MEDEVAC.sqf)
- [ ] [fn_DocRadio_ROTARYPICKUP](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocRadio_ROTARYPICKUP.sqf)
- [ ] [fn_DocRadio_SPOTREP](https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/documents/fn_DocRadio_SPOTREP.sqf)

# I want to help!
Past text here in a code block or do a pull request changing or updating the file in question.
```
Code block:
``` ```
```

**Comment by Robot-Panda15** [comment]
The only one that definitively needs an update is the CFF one.
Will work with Company Staff to check on the others
