### ISSUE TITLE
Change LR 16 to "FARP REQUESTS" and only have 1 Convoy Net

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/cScripts#273]
LR 16 will be utilized for FARP Requests and only 1 Convoy Net needs to be utilized

**Comment by ColdEvul** [comment]
Radios is revived by this getter based on squad name. 
https://github.com/7Cav/cScripts/blob/master/cScripts/CavFnc/functions/players/fn_getRadioChannel.sqf

**Comment by Robot-Panda15** [comment]
that is only for the squad radios, correct? what about the 152 long range radios?

**Comment by ColdEvul** [comment]
both long range and squad radio.
the long range is the one with a short number the squad is the long list.

**Comment by Robot-Panda15** [comment]
I can't find the one for the Convoy nets, would they be located at a different one

**Comment by ColdEvul** [comment]
this i think channel 16 and 17 is the convoy net. 
https://github.com/7Cav/cScripts/blob/master/cScripts/Loadouts/script/CfgPoppy.hpp#L13

whould be cool to get vehicles to tunen in to them automaticly on init
