### ISSUE TITLE
Reconvert RHS MAAWS and launchers to TF47

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/cScripts#315]
Once Grey's patch is added to CAVPACK

**Comment by ColdEvul** [comment]
Pack added 
Classname for new munition> `cav_m3maaws_heat_cs`

**Comment by Robot-Panda15** [comment]
it's not showing up in the arsenals. are we sure this is added?

**Comment by ColdEvul** [comment]
Due to miss coms it was not. It will be in next version.

**Comment by ColdEvul** [comment]
how does it look on this?
