### ISSUE TITLE
Training script system

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#394]
Function not avalible if in a non training or sandbox setting. 
- [ ] Menu system to curator and DI units (Ace Action and Add action) 
- [x] Freez mission Ai and ai controlled vics
- [x] Make all player immortal
- [ ] Injur all players in body part
- [x] Heal all players
- [x] Regear all players
- [ ] Select loadout for player
- [ ] Injur selected player (Done in aries?)
- [ ] Add safe weapon moduel
- [ ] Add zeus action manually setting player loadout.

**Comment by micahwhitsel** [comment]
Idea to add: enabling bullet tracers (as used in the BI Virtual Arsenal) for instructors

The player injury script should no longer be needed as ares handles this well now. Operator error

**Comment by ColdEvul** [comment]
> Idea to add: enabling bullet tracers (as used in the BI Virtual Arsenal) for instructors
It's a awesome system tho it only work for one client at the time. So for demonstrational purposes it won't work. I'm afraid. :(
[BIS_fnc_traceBullets](https://community.bistudio.com/wiki/BIS_fnc_traceBullets) 

> The player injury script should no longer be needed as ares handles this well now. Operator error

**Comment by micahwhitsel** [comment]
Add a change time script. Either 6 or 12 hours

**Comment by ColdEvul** [comment]
There are a vanilla zen and aries moduel for that don't think it whould help that much due to moon and cloud.

**Comment by micahwhitsel** [comment]
> There are a vanilla zen and aries moduel for that don't think it whould help that much due to moon and cloud.

That can just be a pain to use because of the huge lag spike created going into zeus, dropping the module, and trying to select an appropriate time via a slide. It's just a simple quality of life thing for switching to night. Pretty much everything here can already be done via zeus, just not very conveniently

**Comment by ColdEvul** [comment]
Lagspike will still be there.
I can check if I can use the model code for time change.

Don't whant the old mid night and midday op with fog and clear weather desync :P
