### ISSUE TITLE
Lancer Crate Not Working

### ISSUE THREAD

**Issue by VinoEtCaseus** [7Cav/cScripts#480]
**cScripts Version:** `4.3.11` (stable)

**Description:**
- crates with "Lance" or "Lancer" in params do nothing
- Lancer Composition has "Lance" param in it
- Missing Lancer in Starter Crate Module for Achilles. 
- I know I am missing other things with the loadout system. Please reply if you know. 

**Steps to reproduce:**
- Place down Lancer composition
- Look in crate

**Where did the issue occur?**
- Everywhere

**RPT log file:**
- N/A

**Comment by VinoEtCaseus** [comment]
How do I assign myself? This is a reminder for myself before I go to sleep,

**Comment by VinoEtCaseus** [comment]
Nvm

**Comment by ColdEvul** [comment]
fixed in #477
