### ISSUE TITLE
Remove mortar textures

### ISSUE THREAD

**Issue by micahwhitsel** [7Cav/cScripts#497]
Requesting that the McGehee mortar textures be removed to reduce the overall mission file size by ~2768kb.

**Comment by ColdEvul** [comment]
This should be moved to a mod mortar.

# De note:
To do this it requires
- Mortar Classname Based on existing mortar
- Add hidden texture selection for the mortar
- Add a backpack Classname for the mortar
- Reference the mortar in the backpack and reference the backpack (I think) in the mortar.

**Comment by Robot-Panda15** [comment]
I have the files backed up, will be resizing them to fit the new mortars we're using once I figure out what I'm doing. We're good to remove this.

**Comment by ColdEvul** [comment]
was thinking of moving it over to cavAddon but it's in the git history so it is recoverable as well.
I will comence removal next version
