### ISSUE TITLE
Add vehicle restriction script 

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#505]
- [x] Create a restriction script system.
      - Throw out player
      - Throw out and black screen user
- [x] Add restrictor to initVehicle for all vehicles. 
- [x] Add unit variable permission. 
- [x] Add unit class check for vehicles. 
- [x] Add vehicle groups.
- [x] Add cba settings.
      - Set defult off
      - Set public defult on

**Comment by VinoEtCaseus** [comment]
Are we borrowing from the JB scripts?

**Comment by ColdEvul** [comment]
Was thinking writing one that works without manual hands-on and being toggable.

Is should support gui or steam id. is the thought :)
