### ISSUE TITLE
Viewdistance script appears to be defined twice

### ISSUE THREAD

**Issue by Jaidendude** [7Cav/cScripts#528]
**cScripts Version:** 
Latest

**Description:**
- Viewdistance appears to be defined twice

**Steps to reproduce:**
- cScripts is in on a mission, and this appears each time the missions are loaded

**Where did the issue occur?**
- Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- No RPT file but here's a screenshot https://i.gyazo.com/bd5af070c7d127600fbc8124c84ee1e5.png

**Comment by ColdEvul** [comment]
Have you installed this version without any other packages or have you used it in combination with something?

The alive version have a fork of cScripts. I have not experienced this issue my self when testing.

**Comment by ColdEvul** [comment]
Issue located by tac2 dev issue in the mission

**Comment by davidcit646** [comment]
can confirm, RscEdit is also defined in scripts/common.hpp
