### ISSUE TITLE
Diary record for grid reading

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#531]
Add coordinate and map reading tool diary record.

**Comment by uaon** [comment]
Can you link where diary records are maintained in the cScripts framework?
I might be able to make a <html> + sqf diary entry that will explain that. Also need to know if adding additional .paa or like image files is unwanted. @ColdEvul

**Comment by ColdEvul** [comment]
Here are all present documents images are located in the data folder links provided below.
Images can be png or jpeg as well as paa. paa however always need to be 2^x2^ (2x2 2x4 4x2 512x512 512x1024)

https://github.com/7Cav/cScripts/tree/master/cScripts/CavFnc/functions/documents
https://github.com/7Cav/cScripts/tree/master/cScripts/Data/Images
