### ISSUE TITLE
Add training classnames and inventory

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#553]
Add training classnames and inventory
https://github.com/7Cav/7thCavalry_Training_Missions/issues/10

**Comment by VexA3** [comment]
The linked issue was deleted. Is this still needed?

Reference: https://github.com/7Cav/arma3-training-missions/issues/10

**Comment by ColdEvul** [comment]
part of the fix is here:
https://github.com/7Cav/7CavAddon/pull/108
and here:
https://github.com/7Cav/cScripts/blob/master/cScripts/Loadouts/CfgLoadouts_TrainingClass.hpp

Whant is needed is that they are merged so they correspond.

cScripts are referencing RHS classes so new CavAddon classes is needed to be created.
