### ISSUE TITLE
Create Night Variants of loadouts

### ISSUE THREAD

**Issue by Robot-Panda15** [7Cav/cScripts#674]
Create night variants of loadouts for easy switch into. Essentially less colored smoke, more chemlights of various colors, vanilla Starter Pistols with a set of each color flare for TL+

**Comment by peteoftheworld** [comment]
@Robot-Panda15 @ColdEvul do we have company approved loadouts for this yet?

**Comment by ColdEvul** [comment]
> @Robot-Panda15 @ColdEvul do we have company approved loadouts for this yet?

Highly likely not
We can however put in our own muckup as
`loadoutNight = [];`
this loadout will be automatically set to protected (1) and only obtainable via Loadout selection crate for now. If implemented

**Comment by Robot-Panda15** [comment]
Not needed. Current loadouts make it easy to swap into night centric kits.
