### ISSUE TITLE
Ares Error

### ISSUE THREAD

**Issue by RaynorD** [7Cav/cScripts#68]
I'm getting [this error](https://i.imgur.com/wu8YZiI.png) when starting a mission with use7cavZeusModuels set 1 in CfgSettings. I have not messed with adding any zeus modules, I'm running cScripts stock except for custom insignia. Ares was removed from the modpack in one of the last couple of updates, so the focus of this issue should really be to remove Ares dependence.

File: cScripts/cScripts/CavFnc/functions/init/fn_initModuels.sqf

**Comment by ColdEvul** [comment]
Fixed in #65
It is a eden load issue.
Achillies use aries names still. Cause it is a continued development.
