### ISSUE TITLE
Mission Select CTD

### ISSUE THREAD

**Issue by RaynorD** [7Cav/cScripts#69]
I am getting a file not found crash to desktop at the mission select screen, caused by the CBA mission macro include in cScripts\script_component.hpp (#48). CBA is running and I can join the training servers without issue. Commenting out the line prevents the crash. It occurs both while hosting the mission from the server browser and on a dedicated server, but not when launched from within eden, either singleplayer or multiplayer. This arma issue may be related: https://feedback.bistudio.com/T85815

**Comment by ColdEvul** [comment]
Shit glad I did not att the Debug system cause it used the cba scripts.
Nice find. Will see if the cba people know of the reason and if they know of a bypass.
