### ISSUE TITLE
ACE Medical settings overwriting mission settings

### ISSUE THREAD

**Issue by peakzero** [7Cav/cScripts#703]
This is an edge case for sure, but CPT Storm made a mission file that modifies the ACE medical settings to allow for 68W section practice to practice medical treatment on injured AI.

Unfortunately the training servers configuration overrides the medical settings in the mission file, Is is possible to have a way to use mission specific settings for this use case?

Ticket with mission file for reference https://7cav.us/tickets/524/

**Comment by ColdEvul** [comment]
![image](https://user-images.githubusercontent.com/13811113/113488276-40b0f200-94bd-11eb-8201-9098eb9c8f3e.png)
System works as intended; Mission settings (`cbaSettings.sqf`) override server settings when they are pressent and set to `force force setting_global_dummy_Name` in the `cbaSettings.sqf`.

Tracking

**Comment by peakzero** [comment]
I didn't realize Storm had contacted you separately, apologies. I'll close this.
