### ISSUE TITLE
Starter Crate Presets

### ISSUE THREAD

**Issue by RaynorD** [7Cav/cScripts#72]
It would be really helpful if we had some kind of MOS presets for the starter crate insignia and quick selections, since we can't show everyone all the insignia and loadouts. Currently the only way (I've found) to customize those is in core cScripts files which would get overwritten with cScripts updates. Customizing the boxes for just our alpha company mission for example, I only show them fixed and rotary loadouts, and alpha company insignia. But I also have an infantry area with squad loadouts, so having multiple starter crate presets for different MOS's would be ideal.

I've got projects piled up right now so just throwing this out while the brainstorm is fresh. I may be able to come back and take a shot at it at some point if you haven't already.

**Comment by ColdEvul** [comment]
Something like this?
https://github.com/7Cav/cScripts/tree/GearReStructure/cScripts/Loadouts

**Comment by ColdEvul** [comment]
I will make a possibility for array selection for the crate and presets are on my mind :)

**Comment by RaynorD** [comment]
Just had an additional idea on this, if you weren't already planning this. We could have it show a different client side crate preset to the player based on what unit type the player is. So pilots would see heli/fixed wing loadouts and A Co insignia, but infantry would see infantry loadouts and insignia, all looking at the same box. But of course all loadouts and insignia are available in the ace interaction menu (unless mission type is set to operation). I think that'd pretty much remove the need for any mission side configuration.

**Comment by ColdEvul** [comment]
I am going to tie variableName to loadouts. :)
Also it whould not be hard to check soldier type of the player class name and make only options available for that :)

**Comment by ColdEvul** [comment]
Current structure structure and function:
Alpha - alpha loadouts all Loadouts selectable via addAction
Bravo - bravo loadouts  squad selectable via addAction 
Charlie - charlie loadouts squad selectable via addAction
Ranger - ranger loadouts all selectable via addAction
Medical - medical loadouts all selectable via addAction as well as a alpha pilot. 
Full - activates all above do not allow add actions but ace selections.

Default is set to none.

New optional parameter is added to the crate requiring correct Platoon variable to be selectable. S3 will always bypass restriction for debugging or help out reasons.

This is applied to the zeus crate is  as well.

**Comment by ColdEvul** [comment]
Fixed
