### ISSUE TITLE
Allow partial vehicle repair for any personnel with a Toolkit

### ISSUE THREAD

**Issue by RaduM84** [7Cav/cScripts#746]
Given the current lack of a dedicated element and MOS for logistics it would be beneficial if any personnel with a Toolkit in their backpack can partially repair a vehicle

**Comment by Robot-Panda15** [comment]
@ColdEvul is this possible? Would make it easier than having to restrict it by classnames. Especially considering the people using it should just have repair perms anyway.

**Comment by Robot-Panda15** [comment]
Another solution, considering toolkits are kinda kit restricted for the most part, would be to change cba settings to allow anyone with a toolkit to do a full repair.

**Comment by ColdEvul** [comment]
it's Loadout specific today it's not that hard to add it to all vehicle related classnames or allow for half repair if toolkit is present.

**Comment by Robot-Panda15** [comment]
Fixed in #769
