### ISSUE TITLE
Units missing loadouts

### ISSUE THREAD

**Issue by ColdEvul** [7Cav/cScripts#773]
[cScripts] (Gear) WARNING: "Cav_B_B_Scout_Alpha_TeamLead_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Scout_Bravo_TeamLead_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Scout_SquadLeader_2_1_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Scout_SquadLeader_2_2_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Scout_SquadLeader_2_3_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Scout_SquadLeader_2_4_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Tank_Commander_Saber_1_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Tank_Commander_Saber_2_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Tank_Commander_Saber_3_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.
[cScripts] (Gear) WARNING: "Cav_B_B_Tank_Commander_Saber_4_F" does not have a class specific loadout. Applying "CommonBlufor" loadout.

**Comment by Robot-Panda15** [comment]
Fixed in #769
