### ISSUE TITLE
ACRE issue thread

### ISSUE THREAD

**Issue by AndreasBrostrom** [7Cav/cScripts#786]
Extract from server RPT:
```log
[ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (1SG.Burton.P - acre_prc152_id_1)
[ACRE] (sys_server) WARNING: Duplicate radio ID found! Attempting replace of (CPL.Liber.N - acre_prc343_id_1)
[ACRE] (sys_data) INFO: Data Sync for acre_player: CPL.Liber.N [12:5851] - 22613.3KB
[ACRE] (sys_server) WARNING: All IDs for class acre_prc343 are taken!
```
RPT from client and server acre breakdown:
https://gist.github.com/AndreasBrostrom/9577db87e007ccdde6e0efda352840d1

Duplicate handling:
https://github.com/IDI-Systems/acre2/blob/7246600c0359b28ffb618e9ba07b814c1f20f3a8/addons/sys_server/fnc_masterIdTracker.sqf#L205

**Comment by ColdEvul** [comment]
Issue seams to persist in 4.3.40

**Comment by ColdEvul** [comment]
https://github.com/IDI-Systems/acre2/issues/1056

**Comment by AndreasBrostrom** [comment]
Manage to reproduce issue, sort of, by use of a broken client missing a model spawned by a zeus player.
Issue with reciving direct- and radio transmissionwith effected client model.

Model were not vissable and not synced to effected client.
Model was not able to send direct or radio transmission to client
Client was not able to recive direct and radio transmission from model.
Other parties could communicate propperly

Message below were printed when client were talking to "blind player":
```
21:52:43 [ACRE] (sys_core) WARNING: START SPEAKING: acre_player [S3_3] could not find a player with ID: 21 10:61, Speaking Type: 0
```

**Comment by AndreasBrostrom** [comment]
Mission log data collection:
- Coming soon

**Comment by AndreasBrostrom** [comment]
**ACRE issues from 06/18/2023:**
- Radios had the old 20 programmed channels for Long Range set, even though there was no ACRE modules in the mission file.
- 1 pilot could not hear FAC over 08.
- 6 people could not hear others over Long Range Radios after halfway through the OP.

[17JUN23_SERVER_Valiant_Hawk_RPT.log](https://github.com/7Cav/cScripts/files/11817074/17JUN23_SERVER_Valiant_Hawk_RPT.log)

**Comment by pool011** [comment]
Switching to TFAR
