### ISSUE TITLE
Need to implement array system for adding cargo.

### ISSUE THREAD

**Issue by pool011** [7Cav/cScripts#959]
Need to implement array system for adding cargo. to starter crate

_Originally posted by @pool011 in https://github.com/7Cav/cScripts/pull/919#discussion_r1276868509_

**Comment by AndreasBrostrom** [comment]
What you mena by that?
The function return a array of objects

```
_x = ["exsampke"] call EFUNC(logistics,getContainer);
_x // return: [["foo", 1],["boo", 1],["aoo", 1]];
```

**Comment by pool011** [comment]
Closing this due to alternative solution
