### ISSUE TITLE
New inventory database fixes and improvments

### ISSUE THREAD

**Issue by AndreasBrostrom** [7Cav/cScripts#962]
Todo:
- [x] #970
- [x] Add radios both TFAR and ACRE radios to list (items are not added if they dont exist so its fine)
- [x] #960 that
- [x] #964
_Originally posted by @AndreasBrostrom in https://github.com/7Cav/cScripts/issues/919#issuecomment-1655302150_

**Comment by pool011** [comment]
Fixed in releasefixes branch
